version: '3.4'
services:
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"

  database:
    image: "mysql:latest"
    ports:
      - "3306:3306"

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017

  prometheus:
    image: prom/prometheus:latest
    command: '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
    ports:
      - 9090:9090
    extra_hosts:
      - host.docker.internal:host-gateway
  
  grafana:
    depends_on:
      - prometheus
    image: grafana/grafana:latest
    volumes:
      - ./monitoring/grafana:/etc/grafana/provisioning
    ports:
      - 3010:3000
