{
 "title": "Template Service",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Subscribers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(serviceId) (subscribed_users{serviceId=\"03\"})",
     "legendFormat": "Total subscribers"
    },
    {
     "expr": "subscribed_users{serviceId=\"03\", serviceIndex=\"0\"}",
     "legendFormat": "Normal subscribers"
    },
    {
     "expr": "subscribed_users{serviceId=\"03\", serviceIndex=\"1\"}",
     "legendFormat": "Premium subscribers"
    }
   ]
  },
  {
   "title": "WEGLD in subscriber SC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "current_fees{tokenID=\"WEGLD-dd8471\"} / 1000000000000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Paying subscribers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "paying_subscribers{serviceId=\"03\", serviceIndex=\"0\"}",
     "legendFormat": "Normal users"
    },
    {
     "expr": "paying_subscribers{serviceId=\"03\", serviceIndex=\"1\"}",
     "legendFormat": "Premium users"
    }
   ]
  },
  {
   "title": "Number of subtracted payments",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "subtracted_user_fees_count{serviceId=\"03\", serviceIndex=\"0\"}",
     "legendFormat": "Normal users"
    },
    {
     "expr": "subtracted_user_fees_count{serviceId=\"03\", serviceIndex=\"1\"}",
     "legendFormat": "Premium users"
    }
   ]
  },
  {
   "title": "API Calls / second",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by() (delta(api_count[1m])) / 60"
    }
   ]
  },
  {
   "title": "Processing Time [1 min interval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(endpoint) (delta(api_cpu_time_sum[1m])) / 1000",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "API Calls / Second [1 min interval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(endpoint) (rate(api_count{code=~\"200|201|304\"}[1m]))",
     "legendFormat": "{{endpoint}} "
    }
   ]
  },
  {
   "title": "Average Response Time [1 min interval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(endpoint) (delta(api_sum[1m])) / sum by(endpoint) (delta(api_count[1m]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "CPU Time [1 min interval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(endpoint) (delta(api_sum[1m])) / 1000",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Nodejs CPU Load [1 min interval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "delta(process_cpu_seconds_total[1m]) / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average CPU Time [1 min interval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(endpoint) (delta(api_cpu_time_sum[1m])) / sum by(endpoint) (delta(api_cpu_time_count[1m]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "External API Avg Response time [ms]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (system) (delta(external_apis_sum{}[1m])) / sum by (system) (delta(external_apis_count{}[1m]))",
     "legendFormat": "{{system}}"
    }
   ]
  },
  {
   "title": "External API Calls / Second [1 min interval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(system) (rate(external_apis_count[1m]))",
     "legendFormat": "{{system}}"
    }
   ]
  },
  {
   "title": "Cached API Hits [1 min interval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(endpoint) (delta(cached_api_hits[1m]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Redis Processing Seconds [1 min interval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (action) (delta(redis_duration_sum{}[1m])) / 1000",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Redis Calls / s [1 min interval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (action) (rate(redis_duration_count{}[1m]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Average Redis Response Time [1 min interval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (action) (delta(redis_duration_sum{}[1m])) / sum by (action) (delta(redis_duration_count{}[1m]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Jobs Execution Duration [10 min interval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job_identifier) (rate(jobs_sum[10m]))",
     "legendFormat": "{{job_identifier}}"
    }
   ]
  },
  {
   "title": "Jobs Execution Percentage [60 min interval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job_identifier) (rate(jobs_sum{}[60m])) / 3600",
     "legendFormat": "{{job_identifier}}"
    }
   ]
  }
 ]
}