global:
  evaluation_interval: 6s # defaults to 1m.
  scrape_interval:     6s # defaults to 1m.
  # scrape_timeout defaults to 10s.

scrape_configs:
  - job_name: 'metrics'
    # metrics_path defaults to '/metrics'.
    # scheme defaults to 'http'.
    static_configs:
    - targets: ['host.docker.internal:4000']
